sever:
  port: 8080
  servlet:
    context-path: /ecommerce-api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3307/ecommerce"
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
api:
  prefix: /api/v1

jwt:
  signerKey: ""
